const request = require('supertest');
const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');

// Force test env so rate limiter is bypassed and OTPs return in dev shape
process.env.NODE_ENV = process.env.NODE_ENV || 'development';
process.env.INIT_SECRET = process.env.INIT_SECRET || 'test-init-secret';

const app = require('../src/app');
const User = require('../src/models/User');

jest.setTimeout(300000);

let mongoServer;

// Token lives in an httpOnly cookie — extract it from Set-Cookie header.
const extractCookie = (res) => {
  const setCookie = res.headers['set-cookie'] || [];
  const tokenCookie = setCookie.find((c) => c.startsWith('token='));
  return tokenCookie ? tokenCookie.split(';')[0] : null;
};

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  await mongoose.connect(mongoServer.getUri());
});

afterAll(async () => {
  await mongoose.connection.close();
  if (mongoServer) await mongoServer.stop();
});

describe('Authentication', () => {
  const testEmail = 'test_wm_user@example.com';
  const testPhone = '0244123456';
  let customerCookie;

  test('Creates a superadmin via init-admin with secret', async () => {
    await User.deleteOne({ role: 'superadmin' });
    const res = await request(app)
      .post('/api/v1/auth/init-admin')
      .send({ secret: process.env.INIT_SECRET });
    expect([201, 409]).toContain(res.status);
  });

  test('Rejects init-admin without valid secret', async () => {
    const res = await request(app)
      .post('/api/v1/auth/init-admin')
      .send({ secret: 'wrong' });
    expect(res.status).toBe(403);
  });

  let testUsername; // captured from registration — auto-generated by the server

  test('Registers a new customer (no password) and returns a username', async () => {
    await User.deleteOne({ email: testEmail });
    const res = await request(app)
      .post('/api/v1/auth/register')
      .field('fullName', 'Test WM User')
      .field('email', testEmail)
      .field('phone', testPhone)
      .field('residentialAddress', '123 Test Street, Accra')
      .field('area', 'Mfoum')
      .field('latitude', '5.6037')
      .field('longitude', '-0.1870')
      .field('binType', 'standard');

    expect(res.status).toBe(201);
    expect(res.body.success).toBe(true);
    expect(res.body.user.role).toBe('customer');
    expect(res.body.user.username).toBeTruthy(); // auto-generated
    testUsername = res.body.user.username;
    expect(extractCookie(res)).toBeTruthy();
  });

  test('Rejects registration with a missing/invalid area', async () => {
    const res = await request(app)
      .post('/api/v1/auth/register')
      .field('fullName', 'No Area User')
      .field('phone', '0244111222')
      .field('residentialAddress', '789 Nowhere')
      .field('latitude', '5.6037')
      .field('longitude', '-0.1870');
    expect(res.status).toBe(422);
  });

  test('Registers a customer WITHOUT an email (email optional)', async () => {
    const phoneOnly = '0249876543';
    await User.deleteOne({ phone: phoneOnly });
    const res = await request(app)
      .post('/api/v1/auth/register')
      .field('fullName', 'Phone Only User')
      .field('phone', phoneOnly)
      .field('residentialAddress', '321 Phone St')
      .field('area', 'Estate')
      .field('latitude', '5.6037')
      .field('longitude', '-0.1870')
      .field('binType', 'standard');

    expect(res.status).toBe(201);
    expect(res.body.user.role).toBe('customer');
    const uname = res.body.user.username;
    expect(uname).toBeTruthy();
    // Then they can log in with username + phone (phone is the password).
    const login = await request(app)
      .post('/api/v1/auth/login')
      .send({ username: uname, phone: phoneOnly });
    expect(login.status).toBe(200);
  });

  test('Rejects duplicate phone registration', async () => {
    const res = await request(app)
      .post('/api/v1/auth/register')
      .field('fullName', 'Another User')
      .field('email', 'different_email@example.com')
      .field('phone', testPhone)
      .field('residentialAddress', '456 Other Street')
      .field('area', 'Oxford')
      .field('latitude', '5.6037')
      .field('longitude', '-0.1870');

    expect(res.status).toBe(409);
  });

  test('Logs in with username + phone and returns auth cookie', async () => {
    const res = await request(app)
      .post('/api/v1/auth/login')
      .send({ username: testUsername, phone: testPhone });

    expect(res.status).toBe(200);
    customerCookie = extractCookie(res);
    expect(customerCookie).toBeTruthy();
  });

  test('Username search returns the registered username', async () => {
    const prefix = testUsername.slice(0, 3);
    const res = await request(app).get(`/api/v1/auth/usernames?q=${prefix}`);
    expect(res.status).toBe(200);
    expect(res.body.data.usernames).toContain(testUsername);
  });

  test('Rejects login with wrong phone (wrong password)', async () => {
    const res = await request(app)
      .post('/api/v1/auth/login')
      .send({ username: testUsername, phone: '0200000999' });
    expect(res.status).toBe(401);
  });

  test('Returns current user profile when authenticated', async () => {
    const res = await request(app)
      .get('/api/v1/auth/me')
      .set('Cookie', customerCookie);

    expect(res.status).toBe(200);
    expect(res.body.data.user.email).toBe(testEmail);
  });

  test('Rejects unauthenticated /auth/me', async () => {
    const res = await request(app).get('/api/v1/auth/me');
    expect(res.status).toBe(401);
  });

  test('Forbids customer from accessing admin endpoint', async () => {
    const res = await request(app)
      .get('/api/v1/admin/dashboard')
      .set('Cookie', customerCookie);
    expect(res.status).toBe(403);
  });
});

describe('Admin & RBAC hierarchy', () => {
  let adminCookie;

  test('Logs in as superadmin', async () => {
    const admin = await User.findOne({ role: 'superadmin' });
    if (!admin) return;

    const res = await request(app)
      .post('/api/v1/auth/login')
      .send({ email: admin.email, password: process.env.ADMIN_PASSWORD || 'Admin@123456' });

    expect(res.status).toBe(200);
    adminCookie = extractCookie(res);
    expect(adminCookie).toBeTruthy();
  });

  test('Superadmin can access admin dashboard (role hierarchy)', async () => {
    if (!adminCookie) return;
    const res = await request(app)
      .get('/api/v1/admin/dashboard')
      .set('Cookie', adminCookie);
    expect(res.status).toBe(200);
    expect(res.body.data).toBeDefined();
  });
});
